#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinydashboard)
library(tidyverse)
library(shinyWidgets)
library(ggplot2)
 


# Define UI
ui <- dashboardPage(

    # Application title
    dashboardHeader(title="Automotive Recall App"),

    # Sidebar tabs and ui components
    dashboardSidebar(
        sidebarMenu(
            # Clickable tabs 
            menuItem("Make Summary",tabName = "make_summary",icon=icon("dashboard")),
            menuItem("Recalls over time",tabName = "hist",icon = icon("chart-bar")),
            menuItem("Modeling",tabName = "modeling",icon=icon("chart-line")),
            menuItem("Notes",tabName = "notes",icon=icon("clipboard"))),
        # Filters 
        uiOutput('make_box'),
        uiOutput('model_box'),
        
        checkboxGroupButtons("level",
                             "Select Level of Summary:",
                             choices=c("Make"="MAKETXT",
                                       "Model"="MODELTXT"),
                             selected = c("MAKETXT"))
        ),
    
        # show the meat and potatoes
        dashboardBody(
            # tabs that will show when the user clicks a corresponding tab in the sidebar
            tabItems(
                tabItem(tabName = 'make_summary',
                        DT::dataTableOutput("table")),
                tabItem(tabName = "hist",
                        plotOutput("hist"),
                        plotOutput("model_graph")),
                tabItem(tabName = "modeling",
                        sliderInput("years","Select age of Automobile (years):",
                                    min=1,max=10,value=5),
                        DT::dataTableOutput("model_detail")),
                tabItem(tabName = "notes",
                        htmlOutput("notes_assumptions"))
            
                )
            
        )
    
)

# Define server logic required to draw a histogram
server <- function(input, output,session) {
    # load data generated by data_load.R
    load("input.RDA")

    output$make_box<-renderUI({
        pickerInput("make_box",
                    "Filter on Make:",
                    choices=makes,
                    selected = makes,
                    multiple=T,
                    options = list(`actions-box`=T))
    })
    
    # create responsive filter options for MODEL
    output$model_box<-renderUI({
        data0<-(data %>% filter(MAKETXT %in% input$make_box) %>% distinct(MODELTXT))[[1]]
        pickerInput('model_box','Filter on Model',
                    choices=sort(data0),
                    selected = sort(data0),
                    multiple=T,
                    options = list(`actions-box`=T))
    })
    
    
    # Apply filters. This df will feed every tab
    pdata<-reactive({
        data %>% 
            filter(MAKETXT %in% input$make_box, 
                   MODELTXT %in% input$model_box,
                   YEARTXT<=2010,
                   days_since>0,
                   days_since<7300) 
    })
    
    # table to show average number of recalls by make or make/model
    output$table <- DT::renderDataTable({
        DT::datatable(pdata() %>% group_by(MAKETXT,MODELTXT,YEARTXT) %>% 
                          summarise(recalls=n()) %>% 
                          group_by(!!!syms(input$level)) %>% 
                          summarise(recalls=sum(recalls,na.rm = T),
                                divisor=n()) %>% 
                          mutate(avg_recalls=round(recalls/divisor,2)) %>% 
                          dplyr::select(input$level,recalls,avg_recalls),
                      rownames = F,
                      colnames = c(unname(col_desc[input$level]),"Total Recall(s)","Avg. Recalls (/Mdl/YR)"),
                      options=list(pageLength=20)
                      )
    })
    # histogram to show frequency of recalls by number of days since first manufatured
    output$hist<-renderPlot({
        
        ggplot(pdata(),aes(x=days_since)) +
            geom_histogram(binwidth = 120,boundary=0,color="black",fill="grey") +
            labs(x="Days Since First Manufactured",y="Count of Recalls")
            
    })
    # output$cummulative<-renderPlot({
    #     ggplot(pdata(),aes(x=days_since))+
    #         geom_histogram(aes(y=cumsum(..count..)), binwidth = 120, boundary = 0,
    #                        color = "black", fill = "grey")
    # })
    
    # Show the same data as the histogram as a scatter plot and map the geometric distribution 
    # The geometric distribution was created in data_load.R
    output$model_graph<-renderPlot({
        holder<-pdata() %>% mutate(ds=floor(days_since/120)*120+60,
                                   total=n()) %>% 
            group_by(ds) %>% summarise(n_recalls=n()) %>% 
            mutate(n_recalls=n_recalls/120/sum(n_recalls),
                   #log_norm=dlnorm(ds,est1[[1]],est1[[2]]),
                   geom=dgeom(ds,est2))
        ggplot(holder,aes(x=ds)) +
            # geom_line(aes(y=log_norm)) +
            geom_line(aes(y=geom)) +
            geom_point(aes(y=n_recalls))+
            labs(x="Days Since First Manufactured",y="Count of Recalls")
    })
    
    # Use the geometric distribution to predict how many more recalls an owner can expect
    #  based on how old the car is
    output$model_detail<-DT::renderDataTable({
        DT::datatable(pdata() %>% group_by(MAKETXT,MODELTXT,YEARTXT) %>% 
                          summarise(recalls=n()) %>% 
                          group_by(!!!syms(input$level)) %>% 
                          summarise(recalls=sum(recalls,na.rm = T),
                                    divisor=n()) %>% 
                          mutate(avg_recalls=round(recalls/divisor,2),
                                 exp_recalls_td=round(avg_recalls*(1-(1-est2)^(input$years*365)),2),
                                 exp_recalls_remain=avg_recalls-exp_recalls_td) %>% 
                          dplyr::select(input$level,avg_recalls,exp_recalls_td,exp_recalls_remain),
                      rownames=FALSE,
                      colnames = c(unname(col_desc[input$level]),
                                   "Total Recalls per Model/Year",
                                   paste0("Expected Recalls through ", input$years, " years"),
                                   "Expected recalls remaining"
                      )
                      
        )
        
    })
    # Notes and Assumptions
    output$notes_assumptions<-renderUI(HTML(
        "<h3> Notes </h3>
        <ul>
        <li> The goal was to provide the user with an estimate for predicting how many future recalls </li>
        <li> The modeling exercise ignored other important variables due to time contraints</li>
        <li> There is clearly a trend of more recalls in more recent years which would have affected the predicted number of recalls.</li>
        <li> This modeling exercise focused on a calculated field called \'Days Since First Manufactured\'</li>
        <li> This field was calculated by subtracting REPORT RECIEVED DATE from BEGIN DATE OF MANUFACTORING</li>
        <li> Any observation missing either of those attributes was dropped</li>
        <li> Due to the ongoing development and release and new models, a cap of 10 years since first manfactured was implemented</li>
        <li> Any models less than 10 years old and any recalls more than 10 years after BEGIN DATE OF MANUFACTURING were removed</li>
        </ul>"
    ))
    
}

# Run the application 
shinyApp(ui = ui, server = server)
